# Generated by Django 2.0.6 on 2018-09-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('CL', 'cliente'), ('RE', 'repartidor')], default='CL', max_length=20, verbose_name='Tipo de usuario'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user_type',
            field=models.CharField(choices=[('CL', 'cliente'), ('RE', 'repartidor')], default='RE', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
