# Generated by Django 2.0.6 on 2018-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='request',
            name='offer',
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('MP', 'Realizar pagos'), ('CB', 'Transportar objetos'), ('OT', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
