# Generated by Django 2.0.6 on 2018-09-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_request_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='decription',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripcion'),
        ),
    ]
