# Generated by Django 2.0.6 on 2018-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_auto_20180919_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('pago', 'Realizar pagos'), ('domicilio', 'Transportar objetos'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
