# Generated by Django 2.0.6 on 2018-09-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_auto_20180919_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='decription',
            new_name='description',
        ),
    ]
