# Generated by Django 2.0.6 on 2018-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_auto_20180919_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('subject', models.CharField(max_length=40, verbose_name='Asunto')),
                ('message', models.TextField(max_length=300, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
