# Generated by Django 2.0.6 on 2018-11-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180916_1257'),
        ('deliveries', '0008_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.CharField(max_length=50, verbose_name='Precio de oferta')),
                ('description', models.TextField(max_length=200, verbose_name='Descripción de oferta')),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('realizada', 'Realizada')], max_length=20, verbose_name='Estado')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Delivery', verbose_name='Repartidor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.Request', verbose_name='Solicitud')),
            ],
        ),
    ]
