# Generated by Django 2.0.6 on 2018-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_requestanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('realizada', 'Realizada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
